# Generated by Django 5.2.8 on 2025-11-21 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('name', models.CharField(help_text='Unique prompt key', max_length=150, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('intent', 'Intent classifiacation'), ('extract', 'Paramter extraction'), ('general_qa', 'GENERAL Q&A')], help_text='Logical type of this prompt', max_length=32)),
                ('content', models.TextField(help_text='Prompt text used as a system prompt for the model')),
                ('is_active', models.BooleanField(default=True, help_text='Only active prompts are available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StrategyPromptMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(help_text='Name of the strategy', max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google_vertexai', 'Google Gemini'), ('huggingface', 'Hugging Face')], help_text='Model provider name', max_length=50)),
                ('model_name', models.CharField(help_text='Model identifier', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Only active strategies should be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extract_prompt', models.ForeignKey(blank=True, help_text='System prompt used by the parameter-extraction node.', limit_choices_to={'is_active': True, 'type': 'extract'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_extract_prompt', to='agent_app.prompt', verbose_name='Extraction Prompt')),
                ('general_qa_prompt', models.ForeignKey(blank=True, help_text='System prompt used by the general Q&A node.', limit_choices_to={'is_active': True, 'type': 'general_qa'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_general_qa_prompt', to='agent_app.prompt', verbose_name='General Q&A Prompt')),
                ('intent_prompt', models.ForeignKey(blank=True, help_text='System prompt used by the intent-classification node.', limit_choices_to={'is_active': True, 'type': 'intent'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_intent_prompt', to='agent_app.prompt', verbose_name='Intent Prompt')),
            ],
            options={
                'verbose_name': ' Prompts mapping',
                'verbose_name_plural': 'Prompts mappings',
                'ordering': ['strategy_name'],
            },
        ),
    ]
